### ISSUE TITLE
The Influxd is crashed when the hinted handoff queue is blocked

### ISSUE THREAD

**Issue by andyli029** [chengshiwen/influxdb-cluster#19] opened 2023-03-13 12:11 UTC
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]
```
lvl=warn msg="Write shard failed with hinted handoff" log_id=0gYb_pSl000 service=write node_id=5 shard_id=7 error="queue is blocked"
```
If this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to localhost:8086; Connection refused


curl -o vars.txt "http://localhost:8086/debug/vars"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to localhost:8086; Connection refused

iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by chengshiwen** [comment] 2023-03-13 12:22
@andyli029 The error is like [Why am I seeing `hinted handoff queue not empty` errors in my data node logs?](https://docs.influxdata.com/enterprise_influxdb/v1.8/troubleshooting/frequently_asked_questions/#why-am-i-seeing-hinted-handoff-queue-not-empty-errors-in-my-data-node-logs) and [Why am I seeing `queue is full` errors in my data node logs?](https://docs.influxdata.com/enterprise_influxdb/v1.8/troubleshooting/frequently_asked_questions/#why-am-i-seeing-queue-is-full-errors-in-my-data-node-logs).
The solutions are as follows:
1. **Solution 1 (recommended)**: Modify [`allow-out-of-order-writes = false`](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#allow-out-of-order-writes--false) to `true`, to improve writing performance
2. **Solution 2**: Modify [`max-pending-writes = 1024`](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#max-pending-writes--1024) to a larger value, to prevent the hinted handoff queue from blocking

**Comment by andyli029** [comment] 2023-03-13 12:49
```
<img width="675" alt="image" src="https://user-images.githubusercontent.com/15212006/224706263-e5113aff-83c2-4b4c-8a7c-e85d9f315f57.png">
```

**Comment by chengshiwen** [comment] 2023-03-14 08:23
Close this issue since it's by design.

**Closed by chengshiwen** 2023-03-14 08:23 UTC
Labels: wontfix, by design
